#include <ESP8266WiFi.h>
#include <ESP_Mail_Client.h>

#define PIR_PIN D5

/* WiFi Credentials */
#define WIFI_SSID "niraj"
#define WIFI_PASSWORD "niraj0000"

/* Email Credentials */
#define SMTP_HOST "smtp.gmail.com"
#define SMTP_PORT 465

#define AUTHOR_EMAIL "sahilbhiwankar34@gmail.com"
#define AUTHOR_PASSWORD "hulb wpiq jzln gdqp"

#define RECIPIENT_EMAIL "sahilbhiwankar34@gmail.com"

/* SMTP Session */
SMTPSession smtp;

/* Motion flag to avoid multiple emails */
bool motionDetected = false;

void setup()
{
  Serial.begin(9600);
  pinMode(PIR_PIN, INPUT);

  Serial.println();
  Serial.print("Connecting to WiFi");

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(500);
  }

  Serial.println();
  Serial.println("WiFi Connected Successfully");
}

void loop()
{
  int motion = digitalRead(PIR_PIN);

  if (motion == HIGH && motionDetected == false)
  {
    Serial.println("Motion Detected!");
    sendEmail();
    motionDetected = true;
  }

  if (motion == LOW)
  {
    motionDetected = false;
  }

  delay(500);
}

void sendEmail()
{
  if (WiFi.status() != WL_CONNECTED)
  {
    Serial.println("WiFi Disconnected");
    return;
  }

  SMTP_Message message;

  message.sender.name = "IoT Security System";
  message.sender.email = AUTHOR_EMAIL;
  message.subject = "⚠ Motion Detection Alert";

  message.addRecipient("User", RECIPIENT_EMAIL);

  String textMsg =
  "Dear User,\n\n"
  "This is an automated security alert from the IoT Monitoring System.\n\n"
  "Motion has been detected by the PIR sensor in the monitored area.\n"
  "Please check the surroundings immediately to ensure safety.\n\n"
  "Sensor: PIR Motion Sensor\n"
  "Event: Motion Detected\n\n"
  "This message was automatically generated by the NodeMCU device.\n\n"
  "Regards,\n"
  "IoT Monitoring Team";

  message.text.content = textMsg.c_str();
  message.text.charSet = "us-ascii";
  message.text.transfer_encoding = Content_Transfer_Encoding::enc_7bit;

  ESP_Mail_Session session;

  session.server.host_name = SMTP_HOST;
  session.server.port = SMTP_PORT;

  session.login.email = AUTHOR_EMAIL;
  session.login.password = AUTHOR_PASSWORD;
  session.login.user_domain = "";

  Serial.println("Connecting to Email Server...");

  if (!smtp.connect(&session))
  {
    Serial.println("Email connection failed");
    return;
  }

  Serial.println("Sending Email...");

  if (!MailClient.sendMail(&smtp, &message))
  {
    Serial.println("Error sending Email");
    Serial.println(smtp.errorReason());
  }
  else
  {
    Serial.println("Email Sent Successfully!");
  }

  smtp.closeSession();
}